-- Tạo user/schema
CREATE USER admin IDENTIFIED BY 09012001;
GRANT CONNECT, RESOURCE TO admin;

-- Đăng nhập với user vừa tạo
ALTER SESSION SET CURRENT_SCHEMA = admin;

-- Tạo bảng sản phẩm
CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255),
    description VARCHAR2(1000),
    price NUMBER(12,2),
    image_url VARCHAR2(255),
    category VARCHAR2(100)
);

-- Tạo bảng tài khoản
CREATE TABLE accounts (
    account_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) UNIQUE,
    password VARCHAR2(100),
    email VARCHAR2(255),
    full_name VARCHAR2(255),
    created_at DATE DEFAULT SYSDATE
);

-- Tạo bảng giỏ hàng
CREATE TABLE cart (
    cart_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id NUMBER REFERENCES accounts(account_id),
    product_id NUMBER REFERENCES products(product_id),
    quantity NUMBER DEFAULT 1
);

-- Tạo bảng đơn hàng
CREATE TABLE orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id NUMBER REFERENCES accounts(account_id),
    order_date DATE DEFAULT SYSDATE,
    total NUMBER(12,2)
);

-- Tạo bảng chi tiết đơn hàng
CREATE TABLE order_items (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER REFERENCES orders(order_id),
    product_id NUMBER REFERENCES products(product_id),
    quantity NUMBER,
    price NUMBER(12,2)
);
